#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config focused_border_color \#EDEDF4
bspc config normal_border_color \#110F0F
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

tint2 &
nitrogen --restore &
nm-applet &
xfce4-power-manager &
fcitx &
picom &
